# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import detect

from PyQt5Browser.main import brow


class Ui_Form(object):
    def switchToRegistration(self):
        result = detect.detection
        if(result[1] == True):
            Form.close()
            brow()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(690, 628)
        self.SignIn = QtWidgets.QPushButton(Form)
        self.SignIn.setGeometry(QtCore.QRect(170, 380, 75, 23))
        self.SignIn.setObjectName("SignIn")
        self.SignIn.clicked.connect(self.switchToRegistration)
        self.Camera = QtWidgets.QLabel(Form)
        self.Camera.setGeometry(QtCore.QRect(140, 30, 371, 231))
        self.Camera.setObjectName("Camera")
        self.SignUp = QtWidgets.QPushButton(Form)
        self.SignUp.setGeometry(QtCore.QRect(400, 380, 75, 23))
        self.SignUp.setObjectName("SignUp")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(290, 330, 81, 21))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SignIn.setText(_translate("Form", "Sign In"))
        self.Camera.setText(_translate("Form", "Camera"))
        self.SignUp.setText(_translate("Form", "Sign Up"))
        self.label_2.setText(_translate("Form", "WELCOME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
