# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegistrationPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from dataSetCreator import insertOrUpdate, createDataSet
from LoginPage import Ui_Form


class Ui_SignUp(object):
    def proceedFace(self):
        userId = self.userIdInputText.text()
        name = self.nameInputText.text()
        password = self.passwordInputText.text()
        mail = self.mailInputText.text()

        insertOrUpdate(userId, name, password, mail)
        createDataSet(userId, name)

    def signUp(self):

        self.window = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window)
        Form.close()
        self.window.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(375, 440)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 60, 111, 21))
        self.label.setSizeIncrement(QtCore.QSize(0, 50))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.nameLabel = QtWidgets.QLabel(Form)
        self.nameLabel.setGeometry(QtCore.QRect(80, 130, 91, 16))
        self.nameLabel.setObjectName("nameLabel")
        self.passwordLabel = QtWidgets.QLabel(Form)
        self.passwordLabel.setGeometry(QtCore.QRect(80, 170, 91, 16))
        self.passwordLabel.setObjectName("passwordLabel")
        self.mailLabel = QtWidgets.QLabel(Form)
        self.mailLabel.setGeometry(QtCore.QRect(80, 220, 101, 16))
        self.mailLabel.setObjectName("mailLabel")
        self.faceDetectionButton = QtWidgets.QPushButton(Form)
        self.faceDetectionButton.setGeometry(QtCore.QRect(80, 270, 221, 31))
        self.faceDetectionButton.setObjectName("faceDetectionButton")
        self.SignUpRegisterPage = QtWidgets.QPushButton(Form)
        self.SignUpRegisterPage.setGeometry(QtCore.QRect(150, 330, 75, 23))
        self.SignUpRegisterPage.setObjectName("SignUpRegisterPage")
        self.nameInputText = QtWidgets.QLineEdit(Form)
        self.nameInputText.setGeometry(QtCore.QRect(180, 130, 113, 20))
        self.nameInputText.setObjectName("nameInputText")
        self.passwordInputText = QtWidgets.QLineEdit(Form)
        self.passwordInputText.setGeometry(QtCore.QRect(180, 170, 113, 20))
        self.passwordInputText.setObjectName("passwordInputText")
        self.mailInputText = QtWidgets.QLineEdit(Form)
        self.mailInputText.setGeometry(QtCore.QRect(180, 220, 113, 20))
        self.mailInputText.setObjectName("mailInputText")
        self.userIdLabel = QtWidgets.QLabel(Form)
        self.userIdLabel.setGeometry(QtCore.QRect(80, 90, 91, 16))
        self.userIdLabel.setObjectName("userIdLabel")
        self.userIdInputText = QtWidgets.QLineEdit(Form)
        self.userIdInputText.setGeometry(QtCore.QRect(180, 90, 113, 20))
        self.userIdInputText.setObjectName("userIdInputText")
        self.passwordInputText.setEchoMode(QtWidgets.QLineEdit.Password)
        self.faceDetectionButton.clicked.connect(self.proceedFace)
        self.SignUpRegisterPage.clicked.connect(self.signUp)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Registration "))
        self.nameLabel.setText(_translate("Form", "Name                 :"))
        self.passwordLabel.setText(_translate("Form", "password          :"))
        self.mailLabel.setText(_translate("Form", "Email                  :"))
        self.faceDetectionButton.setText(_translate(
            "Form", "Proceed to Face Biometric Scan -->"))
        self.SignUpRegisterPage.setText(_translate("Form", "Sign Up"))
        self.userIdLabel.setText(_translate("Form", "User ID             :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_SignUp()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
